# Generated by Django 2.1.7 on 2019-03-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='../static/lm/default_album.jpg', upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(default='../static/lm/default_song.jpg', upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('audioPath', models.CharField(max_length=200)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Player.Album')),
            ],
        ),
    ]
