# Generated by Django 2.1.7 on 2019-03-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='pic',
            field=models.ImageField(default='../static/default_album.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='pic',
            field=models.ImageField(default='../static/default_song.png', upload_to=''),
        ),
    ]
