# Generated by Django 2.1.7 on 2019-03-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0002_auto_20190311_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='pic',
            field=models.ImageField(default='/static/default_album.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='pic',
            field=models.ImageField(default='/static/default_song.png', upload_to=''),
        ),
    ]
