# Generated by Django 2.1.7 on 2019-04-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0005_auto_20190316_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='song',
            name='pic',
            field=models.URLField(blank=True, null=True),
        ),
    ]
